# Generated by Django 5.2.8 on 2025-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_freelancertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=50)),
            ],
        ),
    ]
