# Generated by Django 5.2.8 on 2025-11-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_skill',
        ),
    ]
