# Generated by Django 5.2.8 on 2025-11-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_skilltype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_skilltype',
        ),
    ]
