# Generated by Django 5.2.8 on 2025-11-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_delete_tbl_skilltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_skilltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=50)),
                ('freelancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_freelancertype')),
            ],
        ),
    ]
