# Generated by Django 5.2.8 on 2025-12-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_skilltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=50)),
                ('editor_email', models.CharField(max_length=50)),
                ('editor_contact', models.CharField(max_length=50)),
                ('editor_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('editor_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('editor_password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
