# Generated by Django 5.2.8 on 2025-12-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_verifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_name', models.CharField(max_length=50)),
                ('verifier_email', models.CharField(max_length=50)),
                ('verifier_contact', models.CharField(max_length=50)),
                ('verifier_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('verifier_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('verifier_password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
