# Generated by Django 5.2.8 on 2026-01-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_verifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_duration', models.CharField(max_length=50)),
                ('plan_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
