# Generated by Django 5.2.8 on 2026-01-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_plan',
        ),
    ]
