# Generated by Django 5.2.8 on 2026-02-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_admin',
            name='admin_photo',
            field=models.FileField(null=True, upload_to='Assets/UserDocs/'),
        ),
    ]
