# Generated by Django 6.0.2 on 2026-02-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_admin_admin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_plan',
            name='plan_duration',
            field=models.IntegerField(),
        ),
    ]
