# Generated by Django 6.0.2 on 2026-03-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_alter_tbl_plan_plan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_editor',
            name='editor_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_verifier',
            name='verifier_status',
            field=models.IntegerField(default=0),
        ),
    ]
