# Generated by Django 6.0.2 on 2026-03-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_tbl_editor_editor_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_admin',
            name='admin_photo',
        ),
    ]
