# Generated by Django 5.2.8 on 2025-12-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newsupdatesr',
        ),
    ]
