# Generated by Django 5.2.8 on 2025-12-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_newsupdatesr',
            name='news',
        ),
    ]
