# Generated by Django 5.2.8 on 2025-12-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0004_remove_tbl_newsupdatesr_news'),
        ('Reporter', '0008_tbl_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_newsupdatesr',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reporter.tbl_news'),
        ),
    ]
