# Generated by Django 5.2.8 on 2025-12-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_tbl_verifier'),
        ('Editor', '0006_delete_tbl_newsupdatesr'),
        ('Reporter', '0008_tbl_uploadfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newsupdatesr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsupdatesr_remarks', models.CharField(max_length=50)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_editor')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reporter.tbl_news')),
            ],
        ),
    ]
