# Generated by Django 5.2.8 on 2025-12-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_news',
        ),
    ]
