# Generated by Django 5.2.8 on 2025-12-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_tbl_verifier'),
        ('Guest', '0012_delete_tbl_editor'),
        ('Reporter', '0004_delete_tbl_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_content', models.CharField(max_length=50)),
                ('news_image', models.FileField(upload_to='Assets/news/')),
                ('news_date', models.DateField(auto_now_add=True)),
                ('news_status', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_freelancertype')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_reporter')),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_verifier')),
            ],
        ),
    ]
