# Generated by Django 5.2.8 on 2025-12-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_uploadfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_files', models.FileField(upload_to='Assets/news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reporter.tbl_news')),
            ],
        ),
    ]
