# Generated by Django 5.2.8 on 2026-01-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_verifier'),
        ('Reporter', '0008_tbl_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_news',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory'),
        ),
    ]
