# Generated by Django 5.2.8 on 2026-01-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0009_tbl_news_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_news',
            name='category',
        ),
    ]
