# Generated by Django 5.2.8 on 2026-01-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0010_remove_tbl_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_uploadfiles',
            name='upload_status',
            field=models.IntegerField(default=0),
        ),
    ]
