# Generated by Django 5.2.8 on 2026-02-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0011_tbl_uploadfiles_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_news',
            name='breaking',
            field=models.IntegerField(default=0),
        ),
    ]
