# Generated by Django 6.0.2 on 2026-02-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0012_tbl_news_breaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_news',
            name='news_amount',
            field=models.IntegerField(default=0),
        ),
    ]
