# Generated by Django 6.0.2 on 2026-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0013_tbl_news_news_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_news',
            name='news_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
