# Generated by Django 5.2.8 on 2025-11-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=50)),
                ('reporter_email', models.CharField(max_length=50)),
                ('reporter_contact', models.CharField(max_length=50)),
                ('reporter_gender', models.CharField(max_length=50)),
                ('reporter_dob', models.CharField(max_length=50)),
                ('reporter_password', models.CharField(max_length=50)),
                ('reporter_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('reporter_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
