# Generated by Django 5.2.8 on 2025-11-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_reporter',
            name='reporter_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
