# Generated by Django 5.2.8 on 2025-11-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_reporter_reporter_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_reporter',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
