# Generated by Django 5.2.8 on 2025-11-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0004_remove_tbl_user_place_delete_tbl_reporter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=50)),
                ('reporter_email', models.CharField(max_length=50)),
                ('reporter_contact', models.CharField(max_length=50)),
                ('reporter_gender', models.CharField(max_length=50)),
                ('reporter_dob', models.CharField(max_length=50)),
                ('reporter_address', models.CharField(blank=True, max_length=50, null=True)),
                ('reporter_password', models.CharField(max_length=50)),
                ('reporter_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('reporter_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('reporter_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=80)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('user_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
