# Generated by Django 5.2.8 on 2025-11-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_skilltype'),
        ('Guest', '0006_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_dob', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=80)),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('user_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('user_work', models.CharField(max_length=50)),
                ('user_level', models.CharField(max_length=50)),
                ('user_bio', models.CharField(max_length=50)),
                ('user_media', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_skilltype')),
            ],
        ),
    ]
