# Generated by Django 5.2.8 on 2025-11-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
