# Generated by Django 5.2.8 on 2025-12-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_work',
            field=models.FileField(upload_to='Assets/UserDocs/'),
        ),
    ]
