# Generated by Django 5.2.8 on 2025-12-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_editor',
        ),
    ]
