# Generated by Django 5.2.8 on 2026-01-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
