# Generated by Django 5.2.8 on 2026-01-02 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0008_tbl_uploadfiles'),
        ('User', '0010_tbl_complaint_complaint_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_amount', models.CharField(max_length=50)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reporter.tbl_news')),
            ],
        ),
    ]
