# Generated by Django 5.2.8 on 2026-01-05 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_verifier'),
        ('Guest', '0012_delete_tbl_editor'),
        ('User', '0011_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('editor_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_from', to='Admin.tbl_editor')),
                ('editor_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_to', to='Admin.tbl_editor')),
                ('reporter_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter_from', to='Guest.tbl_reporter')),
                ('reporter_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter_to', to='Guest.tbl_reporter')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
