# Generated by Django 5.2.8 on 2026-01-17 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0011_tbl_uploadfiles_upload_status'),
        ('User', '0012_tbl_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_payment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Reporter.tbl_news'),
        ),
    ]
