# Generated by Django 5.2.8 on 2026-01-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_verifier'),
        ('User', '0013_alter_tbl_payment_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='editor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_editor'),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='verifier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_verifier'),
        ),
    ]
