# Generated by Django 5.2.8 on 2026-01-29 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_plan'),
        ('Guest', '0012_delete_tbl_editor'),
        ('User', '0014_tbl_complaint_editor_id_tbl_complaint_verifier_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.CharField(max_length=50)),
                ('subscription_status', models.IntegerField(default=0)),
                ('subscription_enddate', models.CharField(max_length=50)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_plan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
