# Generated by Django 5.2.8 on 2026-01-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_advertisement',
        ),
    ]
