# Generated by Django 5.2.8 on 2026-01-29 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_plan'),
        ('Guest', '0012_delete_tbl_editor'),
        ('User', '0017_delete_tbl_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_date', models.DateField(auto_now_add=True)),
                ('advertisement_status', models.IntegerField(default=0)),
                ('advertisement_file', models.FileField(upload_to='Assets/news/')),
                ('advertisement_title', models.CharField(max_length=50)),
                ('advertisement_content', models.CharField(max_length=50)),
                ('editor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_editor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('verifier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_verifier')),
            ],
        ),
    ]
