# Generated by Django 5.2.8 on 2026-02-06 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_plan'),
        ('User', '0018_tbl_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_advertisement',
            name='editor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_editor'),
        ),
        migrations.AlterField(
            model_name='tbl_advertisement',
            name='verifier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_verifier'),
        ),
    ]
