# Generated by Django 5.2.8 on 2026-02-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_alter_tbl_advertisement_editor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_advertisement',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_payment'),
        ),
    ]
