# Generated by Django 5.2.8 on 2026-02-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_advertisement_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_advertisement',
            name='payment',
        ),
    ]
