# Generated by Django 5.2.8 on 2026-02-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_remove_tbl_advertisement_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_payment',
        ),
    ]
