# Generated by Django 5.2.8 on 2026-02-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0011_tbl_uploadfiles_upload_status'),
        ('User', '0022_delete_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_amount', models.CharField(max_length=50)),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_advertisement')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Reporter.tbl_news')),
            ],
        ),
    ]
