# Generated by Django 5.2.8 on 2026-02-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_tbl_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_payment',
            old_name='advertisement',
            new_name='advertise',
        ),
    ]
