# Generated by Django 5.2.8 on 2026-02-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_rename_advertisement_tbl_payment_advertise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_payment',
            old_name='advertise',
            new_name='advertise_id',
        ),
    ]
