# Generated by Django 5.2.8 on 2026-02-06 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporter', '0011_tbl_uploadfiles_upload_status'),
        ('User', '0025_rename_advertise_tbl_payment_advertise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_payment',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Reporter.tbl_news'),
        ),
    ]
