# Generated by Django 5.2.8 on 2026-02-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_plan'),
        ('User', '0026_alter_tbl_payment_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_advertisement',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_admin'),
        ),
    ]
