# Generated by Django 5.2.8 on 2026-02-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_tbl_advertisement_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_payment',
            name='advertise_id',
        ),
        migrations.RemoveField(
            model_name='tbl_payment',
            name='news',
        ),
        migrations.DeleteModel(
            name='tbl_advertisement',
        ),
        migrations.DeleteModel(
            name='tbl_payment',
        ),
    ]
