# Generated by Django 5.2.8 on 2026-02-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_plan'),
        ('Guest', '0012_delete_tbl_editor'),
        ('Reporter', '0011_tbl_uploadfiles_upload_status'),
        ('User', '0028_remove_tbl_payment_advertise_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_date', models.DateField(auto_now_add=True)),
                ('advertisement_status', models.IntegerField(default=0)),
                ('advertisement_file', models.FileField(upload_to='Assets/news/')),
                ('advertisement_title', models.CharField(max_length=50)),
                ('advertisement_content', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_admin')),
                ('editor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_editor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('verifier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_verifier')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_amount', models.CharField(max_length=50)),
                ('advertise_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_advertisement')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Reporter.tbl_news')),
            ],
        ),
    ]
