# Generated by Django 5.2.8 on 2026-02-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_tbl_advertisement_tbl_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_advertisement',
            name='admin_id',
        ),
    ]
