# Generated by Django 5.2.8 on 2026-02-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_plan'),
        ('User', '0030_remove_tbl_advertisement_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chat',
            name='admin_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_from', to='Admin.tbl_admin'),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='admin_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_to', to='Admin.tbl_admin'),
        ),
    ]
