# Generated by Django 6.0.2 on 2026-02-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_admin_admin_photo'),
        ('Guest', '0012_delete_tbl_editor'),
        ('User', '0031_tbl_chat_admin_from_tbl_chat_admin_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_advertisement',
            name='advertisement_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='tbl_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField(auto_now_add=True)),
                ('salary_amount', models.IntegerField()),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_editor')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_reporter')),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_verifier')),
            ],
        ),
    ]
