# Generated by Django 6.0.2 on 2026-02-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_tbl_advertisement_advertisement_amount_tbl_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subscription',
        ),
    ]
