# Generated by Django 6.0.2 on 2026-02-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_admin_admin_photo'),
        ('Guest', '0012_delete_tbl_editor'),
        ('User', '0033_delete_tbl_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('subscription_status', models.IntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
